name: CI - Verification HTML
on:
  push:
    branches: [ "main" ]
jobs:
  test-final:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Validation
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          files: "[index.html]"